export const site = {
  name: "모퉁이",
  legalName: "아기돌풍",
  businessName: "아기돌풍",
  brand: "모퉁이",
  domain: "www.motungistudio.com",
  apexDomain: "motungistudio.com",
  url: "https://www.motungistudio.com",
  logo: "/brand/icon-512.png",
  ogImage: "/brand/og-image.png",
  twitterImage: "/brand/twitter-image.png",
  description:
    "모퉁이는 아기돌풍이 운영하는 감각적인 굿즈 공식스토어입니다. 일상의 모퉁이에 놓이는 작은 오브제, 선물 패키지, 의미 있는 악세사리를 차분한 톤으로 제안합니다.",
  keywords: [
    "모퉁이",
    "모퉁이 스튜디오",
    "motungistudio",
    "motungi studio",
    "motungi",
    "모퉁이 굿즈",
    "모퉁이 자사몰",
    "모퉁이 쇼핑몰",
    "모퉁이 공식스토어",
    "감각적인 굿즈",
    "디자인 굿즈",
    "라이프스타일 굿즈",
    "오브젝트 브랜드",
    "오브제 브랜드",
    "선물 굿즈",
    "기프트 스토어",
    "아기돌풍",
    "크리스찬 굿즈",
    "기독교 굿즈",
    "교회 굿즈",
    "기독교 선물 굿즈",
    "십자가 굿즈",
    "크리스찬 악세사리",
    "기독교 악세사리",
    "십자가 목걸이",
    "십자가 팔찌",
    "기도 팔찌",
    "기독교 선물",
    "교회 선물",
    "소모임 선물",
    "세례 선물",
    "입교 선물",
    "수련회 선물",
    "크리스천 주얼리",
    "모퉁이 collection",
    "The Quiet Cross Series",
    "모퉁이 news",
    "Season Letter 2026",
    "크리스찬 악세사리 신제품",
    "모퉁이 collaboration",
    "크리스찬 협업",
    "교회 선물",
    "소모임 선물",
    "아기돌풍 사업자 정보",
    "김종란 대표",
    "모퉁이 business",
    "모퉁이 사업자 정보",
    "435-50-01307",
    "모퉁이 contact",
    "모퉁이 문의",
    "아기돌풍 문의",
    "크리스찬 악세사리 문의",
    "기독교 선물 문의",
    "도매 및 소매업",
    "해외직구대행업",
  ],
  openingDate: "2026-06-01",
  issuedDate: "2026-06-02",
  businessRegistration: "435-50-01307",
  owner: "김종란",
  email: "hello@motungistudio.com",
  businessType: "도매 및 소매업",
  businessItem: "해외직구대행업",
};

export const products = [
  {
    src: "/images/motungi/product-cross-necklace.webp",
    alt: "브러시드 실버 십자가 목걸이",
    title: "quiet cross pendant 58,000원",
    price: "58000",
    detail: "브러시드 실버, 스카이블루 에나멜 포인트",
  },
  {
    src: "/images/motungi/product-seed-ring.webp",
    alt: "겨자씨를 담은 골드 링",
    title: "mustard seed ring 64,000원",
    price: "64000",
    detail: "작은 믿음을 담은 골드 포인트 링",
  },
  {
    src: "/images/motungi/product-prayer-bracelet.webp",
    alt: "가죽 기도 팔찌와 실버 십자가 참",
    title: "daily prayer bracelet 42,000원",
    price: "42000",
    detail: "가죽 스트랩과 미니멀 십자가 참",
  },
];

export const services = [
  {
    title: "크리스찬 악세사리",
    label: "Christian Accessories",
    description:
      "십자가, 겨자씨, 물고기 상징을 일상에서 착용하기 좋은 목걸이, 링, 팔찌로 재해석합니다.",
    image: "/images/motungi/arrival-2.webp",
  },
  {
    title: "기독교 선물",
    label: "Faithful Gifts",
    description:
      "세례, 입교, 생일, 감사 선물에 어울리는 차분한 패키지와 오래 남는 오브제를 제안합니다.",
    image: "/images/motungi/social-packaging.webp",
  },
  {
    title: "해외직구대행",
    label: "Global Buying Service",
    description:
      "사업자등록증 기준 종목은 해외직구대행업이며, 브랜드 운영과 상품 소싱 범위에 맞춰 확장됩니다.",
    image: "/images/motungi/social-interior.webp",
  },
];

export const stories = [
  {
    src: "/images/motungi/social-packaging.webp",
    alt: "모던 크리스찬 악세사리 선물 패키지",
    meta: "review | 2026.06.01",
    text: "선물하기 좋은 차분한 패키지",
  },
  {
    src: "/images/motungi/social-interior.webp",
    alt: "선반 위에 놓인 십자가 목걸이와 촛불",
    meta: "story | 2026.05.18",
    text: "하루의 시작에 놓아두는 작은 표식",
  },
  {
    src: "/images/motungi/social-wear.webp",
    alt: "십자가 팔찌를 착용하고 컵을 든 손",
    meta: "look | 2026.05.03",
    text: "일상에 자연스럽게 머무는 십자가",
  },
];
